# -*- coding: utf-8 -*-
"""AI-Assignment Fibonacci numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ft2h-pgXouC47Q2_eJLYjTcBZeq1ffmu
"""

def fibonacci(limit):
    a, b = 0, 1
    while a < limit:
        print(a, end=" ")
        a, b = b, a + b

limit = int(input("Enter the limit for Fibonacci numbers: "))
fibonacci(limit)