# -*- coding: utf-8 -*-
"""Positive Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CWNqLCpan9jM4x0XDFLuq07mAJIkPDiH
"""

def print_positive_numbers(input_list):
    positive_numbers = [num for num in input_list if num > 0]
    return positive_numbers

list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

print(" list1:", print_positive_numbers(list1))
print(" list2:", print_positive_numbers(list2))